Controllers/ExtJSController.cs
using System;
using System.Collections.Generic;
using System.Data.Linq;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Spike.Models;
using System.Data.Entity;

namespace Spike.Controllers
{
    public class ExtJSController : BaseController
    {
        //
        // GET: /ExtJS/

        public ActionResult Grid()
        {
            return View();
        }

        public ActionResult GridMasterDetail()
        {
            return View();
        }

        public ActionResult CascadingCombos()
        {
            return View();
        }

        public ActionResult Chart()
        {
            return View();
        }

        public override ActionResult All_Read(int? page, int? limit, int? companyId)
        {
            return base.All_Read(page, limit, companyId);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Spike.Controllers
{
    public class HomeController : Controller
    {        
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Controllers/JQWidgetsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Spike.Models;

namespace Spike.Controllers
{
    public class JQWidgetsController : BaseController
    {
        //
        // GET: /JQWidgets/

        public ActionResult Grid()
        {
            return View();
        }

        public ActionResult GridMasterDetail()
        {
            return View();
        }

        public ActionResult CascadingCombos()
        {
            return View();
        }

        public ActionResult Chart()
        {
            return View();
        }        
    }
}

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Kendo</h2>
@Html.ActionLink("Grid", "Grid", "Kendo")
<br/>
@Html.ActionLink("Grid Master/Detail", "GridMasterDetail", "Kendo")
<br/>
@Html.ActionLink("Cascading comboboxes", "CascadingCombos", "Kendo")
<br/>
@Html.ActionLink("Chart", "Chart", "Kendo")
<br />
@Html.ActionLink("Grid Web Api", "RestKendo", "Kendo")

<h2>DevExpress</h2>
@Html.ActionLink("Grid", "Grid", "DevExpress")
<br/>
@Html.ActionLink("Grid Master/Detail", "GridMasterDetail", "DevExpress")
<br/>
@Html.ActionLink("Cascading comboboxes", "CascadingCombos", "DevExpress")
<br/>
@Html.ActionLink("Chart", "Chart", "DevExpress")

<h2>jqWidgets</h2>
@Html.ActionLink("Grid", "Grid", "JQWidgets")
<br/>
@Html.ActionLink("Grid Master/Detail", "GridMasterDetail", "JQWidgets")
<br/>
@Html.ActionLink("Cascading comboboxes", "CascadingCombos", "JQWidgets")
<br/>
@Html.ActionLink("Chart", "Chart", "JQWidgets")

<h2>ExtJS</h2>
@Html.ActionLink("Grid", "Grid", "ExtJS")
<br/>
@Html.ActionLink("Grid Master/Detail", "GridMasterDetail", "ExtJS")
<br/>
@Html.ActionLink("Cascading comboboxes", "CascadingCombos", "ExtJS")
<br/>
@Html.ActionLink("Chart", "Chart", "ExtJS")